import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {api} from '../../services/api.js';
const blank={title:'',description:'',venue:'',startsAt:'',endsAt:'',capacity:50,memberPriceMinor:0,publicPriceMinor:0,currency:'INR',status:'draft'};
const localTime=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
// @edit:EVENT_FORM — amounts are entered in minor units; no float-to-money conversions.
export default function EventForm(){
 const {id}=useParams();const navigate=useNavigate();const [values,setValues]=useState(blank),[loading,setLoading]=useState(!!id),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({});
 useEffect(()=>{if(!id){setValues(blank);return;}const c=new AbortController();setLoading(true);api(`/organizer/events/${id}`,{signal:c.signal}).then(({data})=>setValues(Object.fromEntries(Object.keys(blank).map(k=>[k,k==='startsAt'||k==='endsAt'?localTime(data[k]):data[k]])))).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>setLoading(false));return()=>c.abort();},[id]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');setFields({});try{const payload={...values,startsAt:new Date(values.startsAt).toISOString(),endsAt:new Date(values.endsAt).toISOString()};await api(id?`/events/${id}`:'/events',{method:id?'PATCH':'POST',body:payload});navigate('/organizer/events');}catch(e){setError(e.message);setFields(e.fields||{});}finally{setBusy(false);}}
 const definitions=[['title','Event title','text'],['venue','Venue','text'],['startsAt','Starts (your local time)','datetime-local'],['endsAt','Ends (your local time)','datetime-local'],['capacity','Seat capacity','number'],['memberPriceMinor','Member price in minor units (INR: paise)','number'],['publicPriceMinor','Standard price in minor units (INR: paise)','number']];
 return <section className="container account-page event-form"><Link to="/organizer/events">← Manage events</Link><h1>{id?'Edit event':'Create an event'}</h1><p className="muted">Prices are integer minor units: 50000 paise = ₹500. Existing registrations retain their original price.</p>{error&&<div role="alert" className="form-error">{error}</div>}{loading?<p role="status">Loading…</p>:<form className="form-card" onSubmit={submit}><div className="event-form-grid">{definitions.map(([key,label,type])=><div className="field" key={key}><label htmlFor={key}>{label}</label><input id={key} type={type} required value={values[key]} maxLength={type==='text'?200:undefined} min={type==='number'?(key==='capacity'?1:0):undefined} step={type==='number'?1:undefined} onChange={e=>setValues({...values,[key]:type==='number'?Number(e.target.value):e.target.value})} aria-invalid={!!fields[key]} aria-describedby={fields[key]?`${key}-error`:undefined}/>{fields[key]&&<span className="field-error" id={`${key}-error`}>{fields[key]}</span>}</div>)}</div><div className="field"><label htmlFor="description">Description</label><textarea id="description" maxLength={5000} value={values.description} onChange={e=>setValues({...values,description:e.target.value})}/></div><div className="event-form-grid"><div className="field"><label htmlFor="currency">Currency</label><select id="currency" value={values.currency} onChange={e=>setValues({...values,currency:e.target.value})}>{['INR','USD','EUR','GBP'].map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label htmlFor="status">Publication status</label><select id="status" value={values.status} onChange={e=>setValues({...values,status:e.target.value})}>{['draft','published','cancelled'].map(s=><option key={s}>{s}</option>)}</select></div></div><button type="submit" disabled={busy} className="button">{busy?'Saving…':'Save event'}</button></form>}</section>;
}
