import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../../services/api.js';
import {money,date} from '../../utils/format.js';
// @edit:TICKET_LAYOUT — pending reservations never display an admission code.
export default function TicketsPage(){
 const [tickets,setTickets]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();setError('');api('/tickets/me',{signal:c.signal}).then(r=>setTickets(r.data)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[retry]);
 return <section className="container account-page"><p className="eyebrow">YOUR NEXT EXPERIENCE</p><h1>My Tickets</h1><p className="muted">Reservations and admission status for your account.</p><button className="button button-secondary" onClick={()=>setRetry(retry+1)}>Refresh tickets</button>{error&&<p role="alert" className="form-error">{error}</p>}{!tickets&&!error&&<p role="status">Loading tickets…</p>}{tickets?.length===0&&<div className="form-card"><h2>No reservations yet</h2><Link to="/events">Explore events</Link></div>}<div className="event-grid tickets-grid">{tickets?.map(ticket=><article className="form-card ticket-card" key={ticket.id}><span className="status-pill">{ticket.checkedInAt?'Checked in':ticket.status==='pending'?'Pending confirmation':ticket.status}</span><h2>{ticket.eventTitle}</h2><p>{ticket.eventVenue}</p><p>{date(ticket.eventStartsAt)}</p><p>Reserved price: <strong>{money(ticket.priceMinor,ticket.currency)}</strong></p><p className="reference">Reference: {ticket.id}</p>{ticket.admissionCode?<><label htmlFor={`code-${ticket.id}`}>Admission code — show authorized event staff</label><textarea id={`code-${ticket.id}`} readOnly value={ticket.admissionCode} rows={3}/></>:<p className="payment-note">{ticket.status==='pending'?'Your seat is reserved. Await authorized confirmation; this is not yet an admission ticket.':ticket.codeStatus==='reissue_required'?'This legacy ticket needs code reissue by the organizer. No valid admission code is available here.':'No admission code is available for this ticket’s current event/status.'}</p>}</article>)}</div></section>;
}
